sudo: required
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
services: 
  - docker
before_install:
    - docker build -t oscarfouoma/demo-web-app .
script:
  - docker run -p 80:80 oscarfouoma/demo-web-app

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockerapp"
  env: "Dockerapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-667277902999"
  bucket_path: "dockerapp"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY